version: "3.7"

services:
  ecommerce_backend-api:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.docker
    image: amcom/api
    container_name: amcom-api
    command: gunicorn -b 0.0.0.0:4000 config.wsgi
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    depends_on:
      - docker_db
    networks:
      - postgres_network

  docker_db:
    image: postgres:11.3-alpine
    container_name: ecommerce_backend-docker_db
    restart: always
    environment:
      - POSTGRES_DB=ecommerce_backend_db
      - POSTGRES_USER=ecommerce_backend_user
      - POSTGRES_PASSWORD=IWKdrWWnc6XA39pgX6PU
    volumes:
        - postgres_ecommerce_backend_docker:/var/lib/postgresql/data
    networks:
      postgres_network:
         aliases:
            - db

volumes:
  postgres_ecommerce_backend_docker:
    driver: local
    name: postgres_ecommerce_backend_docker

networks:
  postgres_network:
    driver: bridge

