deployment:
  image: "jedivim/amcom:0.1"
  numReplicas: 3
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
ingress:
  host: "minikube.local"
