apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-service
  labels:
    app.kubernetes.io/name: postgres-service
spec:
  ports:
   - port: 5432
  selector:
    app.kubernetes.io/name: postgres
