apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  CREATE_DATABASE: "True"
  POSTGRES_DB: "ecommerce_commerce_db"
  POSTGRES_USER: "ecommerce_commerce_user"
  POSTGRES_PASSWORD: "IWKdrWWnc6XA39pgX6PU"
