apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-api 
spec:
    selector:
        matchLabels:
            name: {{ .Release.Name }}-api
    {{- if not .Values.deployment.autoscaling.enabled }}
    replicas: {{ .Values.NumReplicas }}
    {{- end }}
    template:
        metadata:
            labels:
                name: {{ .Release.Name }}-api
        spec:
            containers:
            - name: {{ .Release.Name }}-api
              image: jedivim/{{ .Release.Name }}:1.2
              command: 
                - /bin/sh 
                - -c 
                - ./docker_start.sh
              envFrom:
                  - configMapRef:
                      name: {{ .Release.Name }}-configmap
              ports:
                  - containerPort: 4000
