apiVersion: v1
kind: Service
metadata:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-service
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    name: {{ .Release.Name }}-api
